### ISSUE TITLE
Add Linear search and Binary search algorithm in C++/Algorithm folder

### ISSUE THREAD

**Issue by risingstar-bit** [risingstar-bit/Compose-Community#89] opened 2022-10-10 10:02 UTC
Add README file for each algorithm in their respective folder. Example C++/Algorithm/BinarySearch folder contains - binary_search (source file) and README.md file

**Comment by vsiddharth365** [comment] 2022-10-10 10:06
Please assign this to me.

**Comment by risingstar-bit** [comment] 2022-10-10 10:28
> Please assign this to me @risingstar-bit

assigned

**Comment by Arcturus22** [comment] 2022-10-20 07:21
Is this issue still open?
I would like to resolve this issue.

**Comment by vsiddharth365** [comment] 2022-10-20 10:58
> Is this issue still open? I would like to resolve this issue.

The issue is already resolved @risingstar-bit

**Closed** 2023-10-02 07:54 UTC
Labels: hacktoberfest
